import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile, stat } from 'node:fs/promises';
import { dirname, join, resolve, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const projectDirectory = resolve(dirname(fileURLToPath(import.meta.url)), '..');

async function filesWithin(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const lists = await Promise.all(entries.map((entry) => {
    const path = join(directory, entry.name);
    if (entry.name.startsWith('.')) return [];
    return entry.isDirectory() ? filesWithin(path) : [path];
  }));
  return lists.flat();
}

/** Run only after Vite has emitted every asset; exported for fixture testing. */
export async function buildServiceWorker(outputDirectory = join(projectDirectory, 'dist')) {
  const required = ['index.html', 'manifest.webmanifest', 'assets/icons/icon-192.png',
    'assets/icons/icon-512.png', 'assets/icons/maskable-512.png', 'assets/icons/apple-touch-icon.png'];
  for (const path of required) {
    if (!(await stat(join(outputDirectory, path))).isFile()) throw new Error(`Missing PWA file: ${path}`);
  }
  const files = (await filesWithin(outputDirectory))
    .filter((path) => !['sw.js', 'sw.js.map'].includes(relative(outputDirectory, path)))
    .filter((path) => !path.endsWith('.map'))
    .sort();
  // Bump the protocol salt whenever worker behaviour changes, even if the
  // application files happen to be identical to a previous deployment.
  const hash = createHash('sha256').update('little-bun-service-worker-v2\n');
  const paths = [];
  for (const file of files) {
    const path = relative(outputDirectory, file).split(sep).join('/');
    paths.push(path);
    hash.update(path).update('\0').update(await readFile(file)).update('\0');
  }
  const version = hash.digest('hex').slice(0, 20);
  const html = await readFile(join(outputDirectory, 'index.html'), 'utf8');
  const moduleTag = html.match(/<script\b[^>]*\btype=["']module["'][^>]*>/i)?.[0];
  const shellPath = moduleTag?.match(/\bsrc=["']([^"']+)["']/i)?.[1] || null;
  const source = `/* Generated by scripts/build-sw.mjs. Do not hand edit. */
const VERSION = ${JSON.stringify(version)};
const FILES = ${JSON.stringify(paths, null, 2)};
const BASE = self.registration.scope;
const SHELL = ${JSON.stringify(shellPath)} ? new URL(${JSON.stringify(shellPath)}, BASE).href : null;
const PREFIX = 'little-bun-' + encodeURIComponent(BASE) + '-';
const CACHE = PREFIX + VERSION;
const STATE_CACHE = PREFIX + 'client-state-v2';
const URLS = FILES.map((path) => new URL(path, BASE).href);
const URL_SET = new Set(URLS);
const INDEX = new URL('index.html', BASE).href;
const MARKER = new URL('__little_bun_offline_ready__', BASE).href;
const PREVIOUS = new URL('__little_bun_previous_version__', BASE).href;
const CLIENT_PREFIX = new URL('__little_bun_client__/', BASE).href;
let pendingPrecache;
let activationReady = Promise.resolve();

async function pinClient(id, version) {
  if (!id || !version) return;
  const cache = await caches.open(STATE_CACHE);
  await cache.put(CLIENT_PREFIX + encodeURIComponent(id), new Response(version));
}

async function clientVersion(id) {
  if (!id) return null;
  const cache = await caches.open(STATE_CACHE);
  return (await cache.match(CLIENT_PREFIX + encodeURIComponent(id)))?.text();
}

async function previousVersion() {
  return (await (await caches.open(CACHE)).match(PREVIOUS))?.text();
}

async function rememberPreviousWorker() {
  const active = self.registration.active;
  if (!active) return false;
  // The legacy worker already supports OFFLINE_STATUS, so migration does not
  // require any new JavaScript to be running in an existing game tab.
  const previous = await new Promise((resolve) => {
    const channel = new MessageChannel();
    const timer = setTimeout(() => { channel.port1.close(); resolve(null); }, 5000);
    channel.port1.onmessage = ({ data }) => {
      clearTimeout(timer);
      channel.port1.close();
      resolve(data?.type === 'OFFLINE_STATUS' && data.version ? data : null);
    };
    active.postMessage({ type: 'OFFLINE_STATUS' }, [channel.port2]);
  });
  if (!previous) throw new Error('Previous worker did not respond; keep the existing game');
  if (previous.version === VERSION) return false;
  await (await caches.open(CACHE)).put(PREVIOUS, new Response(previous.version));
  return previous.protocol == null;
}

async function cacheIsComplete() {
  const cache = await caches.open(CACHE);
  const marker = await cache.match(MARKER);
  if (!marker || await marker.text() !== VERSION) return false;
  const entries = await Promise.all(URLS.map((url) => cache.match(url)));
  return entries.every(Boolean);
}

function precache() {
  if (pendingPrecache) return pendingPrecache;
  pendingPrecache = (async () => {
    const cache = await caches.open(CACHE);
    // addAll is a single cache batch: one failed download rejects the entire batch.
    // The completion marker is committed only once the whole batch succeeds.
    await cache.addAll(URLS.map((url) => new Request(url, { cache: 'reload', credentials: 'same-origin' })));
    await cache.put(MARKER, new Response(VERSION, { headers: { 'Content-Type': 'text/plain' } }));
    if (!await cacheIsComplete()) throw new Error('Incomplete offline cache');
  })().finally(() => { pendingPrecache = undefined; });
  return pendingPrecache;
}

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    await precache();
    const migratingLegacy = await rememberPreviousWorker();
    // One-time migration only: the old page has no APPLY_UPDATE handler.
    // Take over after complete caching, but do not navigate or reload any
    // window. A normal cover reload can then load the repaired page protocol.
    if (migratingLegacy && await cacheIsComplete()) await self.skipWaiting();
  })());
  // Protocol-2 updates require an explicit visible-cover request. The legacy
  // exception above changes the controller, never a running document.
});

self.addEventListener('activate', (event) => {
  activationReady = (async () => {
    if (!await cacheIsComplete()) throw new Error('Cannot activate incomplete cache');
    const previous = await previousVersion();
    const windows = (await self.clients.matchAll({ type: 'window', includeUncontrolled: true }))
      .filter((client) => client.url.startsWith(BASE));
    const keep = new Set([CACHE, STATE_CACHE]);
    if (previous) keep.add(PREFIX + previous);
    for (const client of windows) {
      const pinned = await clientVersion(client.id);
      // Keep another tab's in-progress old shell and its same-name artwork
      // together. Persist pins across service-worker process termination.
      const version = pinned || previous || VERSION;
      await pinClient(client.id, version);
      keep.add(PREFIX + version);
    }
    const state = await caches.open(STATE_CACHE);
    const liveIds = new Set(windows.map((client) => CLIENT_PREFIX + encodeURIComponent(client.id)));
    for (const key of await state.keys()) {
      if (key.url.startsWith(CLIENT_PREFIX) && !liveIds.has(key.url)) await state.delete(key);
    }
    // Only this application's obsolete, unused versions are removed. Keep
    // the previous version too, to cover navigation/activation races.
    for (const key of await caches.keys()) {
      if (key.startsWith(PREFIX) && !keep.has(key)) await caches.delete(key);
    }
    await self.clients.claim();
  })();
  event.waitUntil(activationReady);
});

self.addEventListener('message', (event) => {
  if (!['OFFLINE_STATUS', 'PRECACHE_RETRY', 'APPLY_UPDATE'].includes(event.data?.type)) return;
  event.waitUntil((async () => {
    await activationReady;
    let state = 'error';
    try {
      if (event.data.type === 'PRECACHE_RETRY' && !await cacheIsComplete()) await precache();
      state = await cacheIsComplete() ? 'ready' : 'error';
    } catch { /* Keep any previously cached version available when repair fails. */ }
    if (event.data.type === 'APPLY_UPDATE') {
      // Never activate a worker whose complete-cache marker was evicted or
      // whose asset batch did not finish. Repair is an explicit retry.
      if (state === 'ready') await self.skipWaiting();
      event.ports[0]?.postMessage({ type: 'UPDATE_STATUS', state: state === 'ready' ? 'applying' : 'error', version: VERSION });
      return;
    }
    event.ports[0]?.postMessage({ type: 'OFFLINE_STATUS', state, version: VERSION,
      clientVersion: await clientVersion(event.source?.id) || VERSION, shell: SHELL, protocol: 2 });
  })());
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method !== 'GET' || url.origin !== self.location.origin || !url.href.startsWith(BASE)) return;
  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      await activationReady;
      // Serving the cached shell online and offline avoids mixing build versions.
      const cache = await caches.open(CACHE);
      const shell = await cache.match(INDEX);
      if (shell) {
        await pinClient(event.resultingClientId, VERSION);
        return shell;
      }
      try { return await fetch(request); }
      catch { return new Response('尚未完成離線準備，請連線後再試一次。', { status: 503, headers: { 'Content-Type': 'text/plain; charset=utf-8' } }); }
    })());
    return;
  }
  url.search = '';
  url.hash = '';
  event.respondWith((async () => {
    await activationReady;
    const version = await clientVersion(event.clientId) || VERSION;
    const cache = await caches.open(PREFIX + version);
    const cached = await cache.match(url.href);
    if (cached) return cached;
    // A pinned older client may request a retired hashed JS/CSS filename. Its
    // cache is still present; never replace it with new same-name assets.
    if (version === VERSION && URL_SET.has(url.href)) {
      const latest = await (await caches.open(CACHE)).match(url.href);
      if (latest) return latest;
    }
    return fetch(request);
  })());
});
`;
  await writeFile(join(outputDirectory, 'sw.js'), source);
  return { version, assetCount: paths.length, files: paths };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const result = await buildServiceWorker(process.argv[2] ? resolve(process.argv[2]) : undefined);
  console.log(`Offline worker: ${result.assetCount} files, version ${result.version}`);
}
